version: "3"

volumes:
  data:

# The services have a default network, so 
# is unnecessary to define a networkd 
services:
  db:
    image: mariadb:10.11.4
    environment:
      MARIADB_ROOT_PASSWORD: root

      MARIADB_DATABASE: dameunapata
      # MARIADB_USER: killercat
      # MARIADB_PASSWORD: killallthecats

    expose:
      - "3306"

    ports:
      - "3306:3306"

    volumes:
      - data:/var/lib/mysql
  
  backend:
    depends_on:
      - db 

    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "1337:1337"

    volumes:
      - ./config:/home/app/config
      - ./src:/home/app/src
      - ./package.json:/home/app/package.json
      - ./yarn.lock:/home/app/yarn.lock
      - ./.env:/home/app/.env
      - ./public/uploads:/home/app/public/uploads